minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@inialum/*'
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
  - vitest
  - '@vitest/*'
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
overrides:
  'vitest@*': '4.1.10'
  vite: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
